### ISSUE TITLE
ao.send() runs indefinitely in .editor mode

### ISSUE THREAD

**Issue by Manav2808** [permaweb/aos#190]
When i execute the following command in .editor mode:

Command: 
`ao.send({
    Target = "WSXUI2JjYUldJ7CKq9wE1MGwXs-ldzlUlHOQszwQe0s",
    Action = "Get-Real-Data",
    Url = 'https://api.coingecko.com/api/v3/simple/price?ids=bitcoin&vs_currencies=usd'
})`

It returns the response data indefinitely and keeps adding the message to the input box, however, it stops when some other code is executed in .editor mode.

**Comment by Lucifer0x17** [comment]
Hey Manav, It was not the aos issue It was the 0rbit issue. We have resolved it already. Let us now if you face the issue again.

**Comment by Manav2808** [comment]
Yes, it's fixed now.
