### ISSUE TITLE
[Question] - writeFileSync against writeFile

### ISSUE THREAD

**Issue by baptisteauduge** [permaweb/aos#239]
Hello,

I was curious about the use of `writeFileSync` in the code. Would it be more efficient to use `writeFile` instead, considering it's a non-blocking operation?
https://github.com/permaweb/aos/blob/c2444bc2484b24c16a362e1f48c8724b3d1b3a18/src/services/connect.js#L181

I believe using writeFile could potentially improve the performance of the application by preventing the current thread from being blocked. I look forward to hearing your thoughts on this.

**Comment by twilson63** [comment]
It is blocking,  🤔 wouldn't the live update process potentially get in a doom loop if it reads the cursor file for the next set in the feed before the updated cursor is written?

But maybe give it a try and see if you don't run into any issues, and if you think it is safe, then submit a PR?
