### ISSUE TITLE
npm & yarn lock files

### ISSUE THREAD

**Issue by bliotti** [permaweb/aos#257]
Both [yarn.lock](https://github.com/permaweb/aos/blob/main/yarn.lock) and [package-lock.json](https://github.com/permaweb/aos/blob/main/package-lock.json) are present in the root directory. This seems unintentional and may lead to dependency management conflicts. 

[README](https://github.com/permaweb/aos) does not specify which package manager should be used for development.

Moreover, the [.gitpod.yml](https://github.com/permaweb/aos/blob/main/.gitpod.yml) file is configured to use Yarn.

Clarification needed.

**Comment by twilson63** [comment]
lock files removed

yarn is the way....
