### ISSUE TITLE
[BUG] Run 'aos' command get error An Error occurred trying to boot AOS. Please check your access points, if the problem persists contact support.

### ISSUE THREAD

**Issue by CaptainWang98** [permaweb/aos#262]
I'm just following the quick start, but just cant run the aos cmd successfully.
There is no more detail error message, plz help.
I'm using a macbook with intel core.
Using nvm to manage node version(v20.14.0)

macbook aos % aos
          _____                   _______                   _____
         /\    \                 /::\    \                 /\    \
        /::\    \               /::::\    \               /::\    \
       /::::\    \             /::::::\    \             /::::\    \
      /::::::\    \           /::::::::\    \           /::::::\    \
     /:::/\:::\    \         /:::/~~\:::\    \         /:::/\:::\    \
    /:::/__\:::\    \       /:::/    \:::\    \       /:::/__\:::\    \
   /::::\   \:::\    \     /:::/    / \:::\    \      \:::\   \:::\    \
  /::::::\   \:::\    \   /:::/____/   \:::\____\   ___\:::\   \:::\    \
 /:::/\:::\   \:::\    \ |:::|    |     |:::|    | /\   \:::\   \:::\    \
/:::/  \:::\   \:::\____\|:::|____|     |:::|    |/::\   \:::\   \:::\____\
\::/    \:::\  /:::/    / \:::\    \   /:::/    / \:::\   \:::\   \::/    /
 \/____/ \:::\/:::/    /   \:::\    \ /:::/    /   \:::\   \:::\   \/____/
          \::::::/    /     \:::\    /:::/    /     \:::\   \:::\    \
           \::::/    /       \:::\__/:::/    /       \:::\   \:::\____\
           /:::/    /         \::::::::/    /         \:::\  /:::/    /
          /:::/    /           \::::::/    /           \:::\/:::/    /
         /:::/    /             \::::/    /             \::::::/    /
        /:::/    /               \::/____/               \::::/    /
        \::/    /                 ~~                      \::/    /
         \/____/                                           \/____/

Welcome to the ao Operating System.
An Error occurred trying to boot AOS. Please check your access points, if the problem persists contact support.
macbook aos % node -v
v20.14.0
macbook aos %

**Comment by twilson63** [comment]
Q. How to run aos under the environment using a VPN?
A. When you see
Welcome to the ao Operating System.
An Error occurred trying to boot AOS. Please check your access points, if the problem persists contact support.


That indicates maybe you are using a VPN.
So, you can run 
export HTTPS_PROXY=http://127.0.0.1:your_vpn_port 
in your terminal and then run aos or run
HTTPS_PROXY=localhost:your_vpn_port aos
