### ISSUE TITLE
bug(token-blueprint): Balance check should not default to From

### ISSUE THREAD

**Issue by twilson63** [permaweb/aos#269]
# Problem

Sharing an issue I found with the balance handler on the token blueprint yesterday. In the case where the Recipient is not in the balances list, the handler falls back to the balance of the message's sender (From tag), however the handler's response still tags the Account as Recipient.
Better behaviour would probably be to return 0 if they are not present in the Balance list?
Screenshot 2024-06-19 at 7.54.52 AM.png
 

![Image](https://github.com/permaweb/aos/assets/21292/799648bd-ca96-45de-bed2-14b200e49789)

# Solution

If user explicitly requests recipient or target and it does not exist then the balance returned should be zero

**Comment by Lucifer0x17** [comment]
That's a good find. Can I pick up this issue??
