### ISSUE TITLE
An Error occurred trying to contact your AOS process. Please check your access points, and if the problem persists contact support.

### ISSUE THREAD

**Issue by sweet-smail** [permaweb/aos#292]
<img width="1011" alt="image" src="https://github.com/user-attachments/assets/e3644be6-6e41-4f52-906b-bf34b3694c9d">

**Comment by twilson63** [comment]
Please check your VPN

Also check our FAQ in AO Discord Server:

https://discord.com/channels/1210396395643863101/1215587206635323393/1215988920353816717
