### ISSUE TITLE
ao.send bug update aos 2.0

### ISSUE THREAD

**Issue by zyjblockchain** [permaweb/aos#322]
### Test
1. add test code 
<img width="750" alt="image" src="https://github.com/user-attachments/assets/c541adb9-fdfe-44a4-8dc4-9892b46c75ed">

2. test
<img width="782" alt="image" src="https://github.com/user-attachments/assets/2578d582-9827-434f-bb35-7c97f765548f">

3. result
ao.send() https://ao_marton.g8way.io/#/message/pIycJqYJvW1becMNj7_yz8AbXE6j-2uIdLTJZ-Mz8Tw
<img width="1502" alt="image" src="https://github.com/user-attachments/assets/083a71e4-6752-497e-afd2-e01859d86a9c">

Send() https://ao_marton.g8way.io/#/message/HoEUIn-UW9zbd-D_JjRctQGXIbpL-EjinS0p5h_QFxI
<img width="1609" alt="image" src="https://github.com/user-attachments/assets/742ce74b-715f-4a3c-b356-769eb645039e">

### END
After 2.0, cu only handles Send() but not ao.send().
<img width="1200" alt="image" src="https://github.com/user-attachments/assets/7f21bf40-ce4f-47a0-8444-11cbb559f3ed">

**Comment by twilson63** [comment]
Can you make sure `ao` is available in global scope? did you `.upgrade` or is this a new 2.0 process

**Comment by twilson63** [comment]
![Screen Shot 2024-08-13 at 10 26 30 PM](https://github.com/user-attachments/assets/dd805650-87ed-4b16-b398-d1224691eb22)

I am struggling to reproduce

I will keep trying

**Comment by zyjblockchain** [comment]
<img width="382" alt="image" src="https://github.com/user-attachments/assets/aec56db4-6487-4323-80bc-11eea306cfb3">
