### ISSUE TITLE
bug(token blueprint): large token supplies generate error

### ISSUE THREAD

**Issue by hitwill** [permaweb/aos#354]
a bint error is generated for large token supplies:

```lua
{
  "Messages": [],
  "Assignments": [],
  "Spawns": [],
  "Output": "",
  "GasUsed": 0,
  "Error": "[string \".handlers\"]:345: [string \".bint\"]:787: value cannot be represented by a bint"
}
```

This is when eval is run, for example, for 100_000_000 token supply.

See this process for a test error:
https://www.ao.link/#/message/kiatehaCRc-78D6ZU_QoYi1l0QClrwoWlWq1jf4xAfc

**Comment by twilson63** [comment]
if planning to use large initial supply numbers maybe wrap supply in bint before calc

```lua
Balances = Balances or { [ao.id] = utils.toBalanceValue(bint(10000) * 10 ^ Denomination) }
TotalSupply = TotalSupply or utils.toBalanceValue(bint(10000) * 10 ^ Denomination)

```

**Comment by hitwill** [comment]
Confirmed that works.
