### ISSUE TITLE
feat: Feedback Function

### ISSUE THREAD

**Issue by twilson63** [permaweb/aos#70]
* Feedback Process - a chatroom like process that allows the user to submit feedback which notifies all registered participants so that the feedback can be addressed. If considered quality feedback the user gets some points, so the Feedback Process will need to have the ability to mint points and transfer them to some users.

* aos will need to display the following on the splash screen:

```
Confused? Check out the aos cookbook for docs:  https://cookbook_ao.g8way.io
Got feedback? Send it to the ao+aos devs anytime by running Feedback("Your comment here")
```

The Feedback function will submit feedback to the feedback process and the process will return a reply in the users inbox.

**Comment by chives-network** [comment]
Feedback function merge chatroom, chat, token lua into one lua, will can meet your requirements.
