### ISSUE TITLE
feat: Webpage Process Interaction Interface

### ISSUE THREAD

**Issue by twilson63** [permaweb/aos#71]
When you spawn an aos process, the console will generate a web app in the data of the process, this web app shows the Inbox Data in a console feed like thing, and the UI actions on the right in an accordian view where users can click on an action and use some inputs with a submit button.

Still a work in progress on design, but wanted to add as a placeholder to the issues

proposals are welcome, the webpage if embedded in aos should be a single html with self contained stylesheets and scripts or references to stylesheets and scripts on the permaweb, so they can not be removed. Same with fonts and any other asset.

The process could have a UI (Table) Global that defined the shape of the entry form.

```lua
UI = {
    Register = {
        Nickname = "mySampleName",
        Bio = "Just a normal Arweaver in the chat."
    },
    Broadcast = {
        Message = "Hey everyone!"
    },
    Unregister = {}
}
```

Each property could be a potential action, and each property underneath could be a simple input box.

**Comment by 123poorguy** [comment]
I can't wait to test it out.

**Comment by lopezi** [comment]
can we have a more detailed feature requirement for the interface content and features so that I can come up with a design proposal? vanilla stuff for the implementation? tech requirements and or suggestions on what can/cannot be used also useful.
